### ISSUE TITLE
add footer social link animation

### ISSUE THREAD

**Issue by Arman-ali-khan-786** [Arman-ali-khan-786/CardUI#107]

**Comment by Arman-ali-khan-786** [comment]
@Akshun-01  do it again ok and this time make sure you change only footer social icons ok

**Comment by Akshun-01** [comment]
> @Akshun-01 do it again ok and this time make sure you change only the footer social icons ok

ok got it.

**Comment by AtriSukul1508** [comment]
I would like to work on this issue. please let me know what I need to do regarding the footer section.

**Comment by Arman-ali-khan-786** [comment]
> I would like to work on this issue. please let me know what I need to do regarding the footer section.

yeah go ahead

**Comment by ABHAY-Y** [comment]
Can you assign this task to me?

**Comment by Arman-ali-khan-786** [comment]
> Can you assign this task to me?

done

**Comment by Arman-ali-khan-786** [comment]
@ABHAY-Y  and @AtriSukul1508  since you both haven't made any pr so I am removing both of you from the list of assignees,
if you both want to get it assigned again make sure to provide a proper explanation ok..
have a good day!

**Comment by Gautam-666** [comment]
Can you give me a description what you want to change in the footer links??

**Comment by Arman-ali-khan-786** [comment]
> Can you give me a description what you want to change in the footer links??

make the icons size smaller and animation time a bit faster ok, Are you up for it??

**Comment by Gautam-666** [comment]
Ohk ....can you assign me on this one?

**Comment by Arman-ali-khan-786** [comment]
> Ohk ....can you assign me on this one?

done

**Comment by Gautam-666** [comment]
i have done this one you can close it

**Comment by Arman-ali-khan-786** [comment]
> i have done this one you can close it

thanks for reminding me buddy
