### ISSUE TITLE
ui -6 issue 

### ISSUE THREAD

**Issue by Arman-ali-khan-786** [Arman-ali-khan-786/CardUI#136]
Card content is popping out make, so correct the content alignment

**Comment by charvibhargava** [comment]
I can do this. Please assign this to me.

**Comment by Arman-ali-khan-786** [comment]
> I can do this. Please assign this to me.

assigned

**Comment by charvibhargava** [comment]
I have created the pull request. Kindly verify it.

**Comment by Arman-ali-khan-786** [comment]
> I have created the pull request. Kindly verify it.

fetch updates buddy!!

**Comment by charvibhargava** [comment]
hey, why is footer commented out in new updated code?

**Comment by Arman-ali-khan-786** [comment]
> hey, why is footer commented out in new updated code?

it was by mistake, corrections are made you can now fetch the new code base okk

**Comment by charvibhargava** [comment]
okk
