### ISSUE TITLE
fix the opacity of the navbar/header

### ISSUE THREAD

**Issue by Arman-ali-khan-786** [Arman-ali-khan-786/CardUI#14]

**Comment by hs-07** [comment]
@Arman-ali-khan-786  I made it a bit translucent which makes it a bit different and funky.
you wont liked it?

**Comment by Arman-ali-khan-786** [comment]
> @Arman-ali-khan-786 I made it a bit translucent which makes it a bit different and funky. you wont liked it?

when i scroll down the cards and navbar gets mixed so it is not looking good , can u change that??

**Comment by hs-07** [comment]
yes i can @Arman-ali-khan-786

**Comment by hs-07** [comment]
@Arman-ali-khan-786 its done...u can close this issue
