### ISSUE TITLE
in dark mode source code is not visible

### ISSUE THREAD

**Issue by Arman-ali-khan-786** [Arman-ali-khan-786/CardUI#146]

**Comment by maheshtamarakar** [comment]
Do you think I should change "source code" text color to #fff or what you recommend?

**Comment by Arman-ali-khan-786** [comment]
> @Arman-ali-khan-786 Do you think I should change "source code" text color to #fff or what you recommend?

yeah it will be great

**Comment by nitin-pandita** [comment]
anyone still working on it ?

**Comment by maheshtamarakar** [comment]
> > @Arman-ali-khan-786 Do you think I should change "source code" text color to #fff or what you recommend?
> 
> yeah it will be great

onit

**Comment by maheshtamarakar** [comment]
> anyone still working on it ?

yeah

**Comment by maheshtamarakar** [comment]
@Arman-ali-khan-786  created the PR

**Comment by nitin-pandita** [comment]
> > anyone still working on it ?
> 
> yeah

Ok bro 🙌🏻
