### ISSUE TITLE
game

### ISSUE THREAD

**Issue by NaMiKA0305** [Arman-ali-khan-786/CardUI#169]
i have a puzzle game created by html css js as an issue

**Comment by Arman-ali-khan-786** [comment]
> i have a puzzle game created by html css js as an issue

hey @NaMiKA0305, what are you trying to say please explain and how this is related to CardUi do explain it also...
for now, this issue irrelevant so closing it..

**Comment by NaMiKA0305** [comment]
I am saying that I want to add an game project as repo, can you assign that as an issue to me..

**Comment by Arman-ali-khan-786** [comment]
> I am saying that I want to add an game project as repo, can you assign that as an issue to me....

No, I can't, this project is all about Profile cards and Ui effects not about games and all ok... Please read guidelines carefully and contribute in that way only.

**Comment by NaMiKA0305** [comment]
than can i add profile card to your profile

**Comment by Arman-ali-khan-786** [comment]
> than can i add profile card to your profile

you can refer to issue #65

**Comment by NaMiKA0305** [comment]
Sir,
As you can see I sent you my pull request of profile card . Plzz merge it
to your repo.
