### ISSUE TITLE
Adding a new UI card 

### ISSUE THREAD

**Issue by vandana3869** [Arman-ali-khan-786/CardUI#183]

**Comment by vandana3869** [comment]
@Arman-ali-khan-786  can you please assign me this issue?

**Comment by Arman-ali-khan-786** [comment]
> @Arman-ali-khan-786 can you please assign me this issue?

you don't have to create new issue to add your card just request for assignment in issue #65 okk.. this time i am leaving it.. make sure from next time.. okk..

**Comment by Arman-ali-khan-786** [comment]
just make a pr directly and remind me that you created this issue okkk
