### ISSUE TITLE
make the cards responsive 

### ISSUE THREAD

**Issue by Arman-ali-khan-786** [Arman-ali-khan-786/CardUI#2]
if you are adding your Ui card Effect then  make sure it is responsive as well

**Comment by hs-07** [comment]
I will be able to  make them responsive, so please ASSIGN me the task would love to help you..

**Comment by zeeshankhan00** [comment]
I will make the UI responsive, so assign me the task.

**Comment by Arman-ali-khan-786** [comment]
> I will be able to make them responsive, so please ASSIGN me the task would love to help you..

they are already responsive, the issue here is that if you are adding your Card Ui then make them responsive ok. and if you are looking forward to add your own card ui then i  can assign you

**Comment by hs-07** [comment]
ok @Arman-ali-khan-786 ... i got the point which u are trying to explain through this issue.
yes i am interested in adding my card ui .... assign it to me!!

**Comment by sudip004** [comment]
can i add a dark mode button and then any user click this to change the ui

**Comment by Arman-ali-khan-786** [comment]
> can i add a dark mode button and then any user click this to change the ui

wait i will create an issue for that then only okk

**Comment by Anurag30112003** [comment]
Your website is not responsive on Galaxy fold viewport .
![image](https://user-images.githubusercontent.com/79055093/193394348-407a8678-a827-45da-bd8f-9751d3f53efe.png)

**Comment by Anurag30112003** [comment]
Assign me i'll make it responsive.
