### ISSUE TITLE
change the navbar color

### ISSUE THREAD

**Issue by Arman-ali-khan-786** [Arman-ali-khan-786/CardUI#34]

**Comment by Lekanjoy** [comment]
Hello, I would love to work on this issue..

**Comment by Arman-ali-khan-786** [comment]
> Hello, I would love to work on this issue..
go ahead !!

**Comment by Arman-ali-khan-786** [comment]
> Hello, I would love to work on this issue..

nice work but bro change the navbar color and add some padding in header li elements okk... when i hover them it doesn't look good ..ok

**Comment by Arman-ali-khan-786** [comment]
@Lekanjoy any updates ?? are working on this issue??

**Comment by Lekanjoy** [comment]
I already modified it and made a PR which you merged..

**Comment by Arman-ali-khan-786** [comment]
> I already modified it and made a PR which you merged..

yeah but i asked some modifications .. see to that okay

**Comment by Arman-ali-khan-786** [comment]
@Lekanjoy  are you working on it or not ??

**Comment by Lekanjoy** [comment]
Can you recommend the color you want to be used because you keep telling me to change it after I've done it..
