### ISSUE TITLE
resize the image 

### ISSUE THREAD

**Issue by Arman-ali-khan-786** [Arman-ali-khan-786/CardUI#39]
CardUi image is flattened a bit so it's not looking good

**Comment by ArshErgon** [comment]
@Arman-ali-khan-786 not just image, we need to change your font, you background, alignments, the image size (gzip) and many more.

**Comment by Arman-ali-khan-786** [comment]
> @Arman-ali-khan-786 not just image, we need to change your font, you background, alignments, the image size (gzip) and many more.

yeah i know for that i have create separate issues ok so separate pr have to be made

**Comment by Arman-ali-khan-786** [comment]
@ArshErgon  i will assign but wait for october for Hacktoberfest ok

**Comment by sudip004** [comment]
this issue will be closed?....

**Comment by Arman-ali-khan-786** [comment]
> this issue will be closed?....

no @ArshErgon will be assigned to it

**Comment by himanshu251001** [comment]
@Arman-ali-khan-786  assign me

**Comment by ArshErgon** [comment]
Hey @himanshu251001 well I am working on this and I have already started.

**Comment by himanshu251001** [comment]
@himanshu251001 2 or more people can work on it.I think there is no problem in it
