### ISSUE TITLE
change  font style 

### ISSUE THREAD

**Issue by Arman-ali-khan-786** [Arman-ali-khan-786/CardUI#40]
for different sections give font styles yet a good one

**Comment by ArshErgon** [comment]
assign it to me

**Comment by Petsamuel** [comment]
assign this issue to me

**Comment by Noothan-am** [comment]
hey is this repository participating in hacktoberfest 22? I was looking for a contribution.

**Comment by Arman-ali-khan-786** [comment]
> assign it to me

go ahead

**Comment by Arman-ali-khan-786** [comment]
> assign this issue to me

@ArshErgon  is working on it

**Comment by himanshu251001** [comment]
Asign to me

**Comment by ArshErgon** [comment]
I have started working on it.

**Comment by ArshErgon** [comment]
@himanshu251001 do you want to work on this issue?

**Comment by Arman-ali-khan-786** [comment]
@himanshu251001 are you still working on it??

**Comment by IpsitaSenapati** [comment]
@Arman-ali-khan-786 I want to work on this. Please assign me.

**Comment by Arman-ali-khan-786** [comment]
> @Arman-ali-khan-786 I want to work on this. Please assign me.

sure

**Comment by IpsitaSenapati** [comment]
Created the pull request.
