### ISSUE TITLE
add dark and light mode button 

### ISSUE THREAD

**Issue by Arman-ali-khan-786** [Arman-ali-khan-786/CardUI#45]
add a button to switch from light to dark mode and vice versa

**Comment by Anuran12** [comment]
Hi @Arman-ali-khan-786 can you please assign it to me?

**Comment by Arman-ali-khan-786** [comment]
> Hi @Arman-ali-khan-786 can you please assign it to me?

you can also work on it

**Comment by Akshun-01** [comment]
hi @Arman-ali-khan-786 , as I noticed you did not added the light dark mode till now to the site, I have already developed that feature and sent a PR . please review it and merge if u like it

**Comment by Arman-ali-khan-786** [comment]
> hi @Arman-ali-khan-786 , as I noticed you did not added the light dark mode till now to the site, I have already developed that feature and sent a PR . please review it and merge if u like it (I didn't knew we first need to ask maintainer to assign it to us, so I already developed this feature without contacting u.... will make sure to ask beforehand in the future.)

yeah that's right before making a pr to any project or working on any isssue you need to be assigned to it by the author of that project ok

**Comment by Akshun-01** [comment]
> > hi @Arman-ali-khan-786 , as I noticed you did not added the light dark mode till now to the site, I have already developed that feature and sent a PR . please review it and merge if u like it (I didn't knew we first need to ask maintainer to assign it to us, so I already developed this feature without contacting u.... will make sure to ask beforehand in the future.)
> 
> yeah that's right before making a pr to any project or working on any isssue you need to be assigned to it by the author of that project ok

Ok got it.. will keep in mind.
Thnx
