### ISSUE TITLE
Making repo to community standard

### ISSUE THREAD

**Issue by Anurag30112003** [Arman-ali-khan-786/CardUI#49]
Adding Contributing.md , code of conduct.md and license for making repo up to community standard.
![image](https://user-images.githubusercontent.com/79055093/193394485-268fcba4-7d39-471e-b28d-bdb91c22811b.png)

**Comment by Arman-ali-khan-786** [comment]
> Adding Contributing.md , code of conduct.md and license for making repo up to community standard. ![image](https://user-images.githubusercontent.com/79055093/193394485-268fcba4-7d39-471e-b28d-bdb91c22811b.png)

well work on it
