### ISSUE TITLE
ui -7 photo is not linked properly

### ISSUE THREAD

**Issue by Arman-ali-khan-786** [Arman-ali-khan-786/CardUI#51]
@SaikiranVoladri  see to it and others can also work on it

**Comment by shivam-Purohit** [comment]
@Arman-ali-khan-786  can you explain more on the issue , I can take on this if you permit.

**Comment by Arman-ali-khan-786** [comment]
visit : https://arman-ali-khan-786.github.io/CardUI/   and see ui-7 the profile image is not linked properly the image path need to be correct

**Comment by SaikiranVoladri** [comment]
sure

**Comment by shivam-Purohit** [comment]
okay working on it

**Comment by shivam-Purohit** [comment]
it is working properly in my local environment. I change the name from profile photo to profilePhoto to remove any confusion and typing error. Shall I request a pull ?

**Comment by SaikiranVoladri** [comment]
i had resolved that path issue and pushed a PR please check it now

**Comment by Kotak-Prerit** [comment]
remove the whitespace in the file name. then it'll work. You have Change (profile photo.jpg) to (profile_photo.jpg) because whitespace in file name is not allowed.

**Comment by SaikiranVoladri** [comment]
yeah i had fixed it (changed code for my path ) and raised a PR please
merge it
