### ISSUE TITLE
Upper side violet block is looking not so well

### ISSUE THREAD

**Issue by kushaljgec2025** [Arman-ali-khan-786/CardUI#61]
i can fix the issue opening time upper side violet block on light theme is not looking so well
![Screenshot (1)](https://user-images.githubusercontent.com/108950724/193441886-b0d81c86-5cf2-44a4-9257-5fe0eeb246f6.png)

**Comment by kushaljgec2025** [comment]
assign me the task

**Comment by Arman-ali-khan-786** [comment]
> assign me the task

it's navbar , yeah you can work on it

**Comment by Arman-ali-khan-786** [comment]
> > assign me the task
> 
> it's navbar , yeah you can work on it

and make sure to fetch upstream before making a pr

**Comment by Arman-ali-khan-786** [comment]
@kushaljgec2025 are still working on it??

**Comment by kushaljgec2025** [comment]
DONE

**Comment by kushaljgec2025** [comment]
can you add hactoberfest-accepted  tag

**Comment by kushaljgec2025** [comment]
Yupp I will resolve within 1 day . Thanks 🙂🙂
