### ISSUE TITLE
UI-9 social icons not showing properly

### ISSUE THREAD

**Issue by raghav-rama** [Arman-ali-khan-786/CardUI#81]
<div align="center">
<img src="https://user-images.githubusercontent.com/91389059/194666954-2b2a8b2a-8df5-4255-916f-e3fa88e70da0.png" alt="pugh"></img>
</div>

**Comment by raghav-rama** [comment]
please assign this to me

**Comment by Arman-ali-khan-786** [comment]
> please assign this to me

this issue will not be a part of the hacktoberfest ok

**Comment by raghav-rama** [comment]
it hardly matters, i just want to fix my code, that orange color is not looking good

**Comment by Arman-ali-khan-786** [comment]
> it hardly matters, i just want to fix my code, that orange color is not looking good

okayy
