### ISSUE TITLE
Add my Portfolio Card UI

### ISSUE THREAD

**Issue by Anubhavgupta18** [Arman-ali-khan-786/CardUI#84]
![Screenshot (3)](https://user-images.githubusercontent.com/96951519/194711600-55af85b9-4202-4e4d-87cb-d4e7980e44c4.png)
![Screenshot (2)](https://user-images.githubusercontent.com/96951519/194711634-91524dfc-2e15-411d-a559-133b501f6f43.png)

**Comment by Anubhavgupta18** [comment]
Please kindly assign me to contribute my Card UI.

**Comment by Arman-ali-khan-786** [comment]
> Please kindly assign me to contribute my Card UI.

don't create a seperate issue for it see issue #65 ,ask there ok
