### ISSUE TITLE
Full UI rewrite.

### ISSUE THREAD

**Issue by anuragts** [Arman-ali-khan-786/CardUI#86]
The current UI of the website is not stylish and appealing, so I re-designed the website.
Here is my UI mockup -
![image](https://user-images.githubusercontent.com/79055093/194727232-6d5a50a5-7dc6-4583-87f8-a6864037bd4f.png)
![image](https://user-images.githubusercontent.com/79055093/194727747-68101cb5-7919-4134-bff5-e89c2eac4813.png)
![image](https://user-images.githubusercontent.com/79055093/194727250-f84c6a13-1315-48e9-9269-8ecb7808b7c5.png)
![image](https://user-images.githubusercontent.com/79055093/194727759-9badb84e-f267-4119-8c53-22d44165e18e.png)

Here is the design file - https://www.figma.com/file/lRb1m7qWrf7q2OmH9nEHoK/cardui?node-id=0%3A1
We should do a full UI rewrite with modern tech like tailwindcss. 
I can also contribute to the rewrite.

**Comment by Arman-ali-khan-786** [comment]
> The current UI of the website is not stylish and appealing, so I re-designed the website. Here is my UI mockup - ![image](https://user-images.githubusercontent.com/79055093/194727232-6d5a50a5-7dc6-4583-87f8-a6864037bd4f.png) ![image](https://user-images.githubusercontent.com/79055093/194727747-68101cb5-7919-4134-bff5-e89c2eac4813.png) ![image](https://user-images.githubusercontent.com/79055093/194727250-f84c6a13-1315-48e9-9269-8ecb7808b7c5.png) ![image](https://user-images.githubusercontent.com/79055093/194727759-9badb84e-f267-4119-8c53-22d44165e18e.png)
> 
> Here is the design file - https://www.figma.com/file/lRb1m7qWrf7q2OmH9nEHoK/cardui?node-id=0%3A1 We should do a full UI rewrite with modern tech like tailwindcss. I can also contribute to the rewrite.

yeah totally appreciate your work  but this is a beginner friendly open source project , tech stacks will remain the same (the basic one's) , if you want to rewrite  the website ui you need to code in html ,css and js , if your are ok with that , you will be assigned ...

**Comment by Anurag30112003** [comment]
yes, I can do it with vanilla  CSS. And it will also take time.

**Comment by Arman-ali-khan-786** [comment]
@Anurag30112003  do it then

**Comment by Arman-ali-khan-786** [comment]
@Anurag30112003  any updates ??

**Comment by Anurag30112003** [comment]
working on it.

**Comment by Anurag30112003** [comment]
made homepage -
![image](https://user-images.githubusercontent.com/79055093/196745032-b0e33e3a-dd02-4076-b567-51a525774f85.png)
You can also refer 
https://cardui1-212.netlify.app/
https://github.com/Anurag30112003/cardui

**Comment by Arman-ali-khan-786** [comment]
> made homepage - ![image](https://user-images.githubusercontent.com/79055093/196745032-b0e33e3a-dd02-4076-b567-51a525774f85.png) You can also refer https://cardui1-212.netlify.app/ https://github.com/Anurag30112003/cardui

nice one
